export enum MEDIA {
  MOB_SMALL = '@media screen and (max-width: 320px)',
  MOB = '@media screen and (min-width: 375px)',
  MOB_LARGE = '@media screen and (max-width: 425px)',
  MOB_MAX = '@media screen and (min-width: 426px) and (max-width: 767px)',
  TABLET_V = '@media screen and (min-width: 768px)',
  TABLET_V_MAX = '@media screen and (min-width: 426px) and (max-width: 899px)',
  TABLET_H = '@media screen and (min-width: 1024px)',
  BASE_TEMPLATE = '@media screen and (min-width: 1440px)',
  BASE_TEMPLATE_PLUS = '@media screen and (min-width: 1640px)',
  DESKTOP = '@media screen and (min-width: 1300px)',
  MW = '@media screen and (max-width: 899px)',
  MD = '@media screen and (min-width: 900px)',
  MACBOOK_PRO_13 = '@media screen and (max-width: 1440px) and (max-height: 720px)',
  VWD_LAPTOP = '@media screen and (min-width: 900px) and (max-width: 1279px)',
  VWD85_DESKTOP = '@media screen and (min-width: 1280px) and (max-width: 1439px)',
  VWD_DESKTOP = '@media screen and (min-width: 1440px) and (max-width: 1919px)',
  VWD_TV = '@media screen and (min-width: 1920px)',
  SMALL_HEIGHT = '@media screen and (max-height: 880px)',
}
